### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by TanyaKo** [TanyaKo/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by ko-tan1** [comment]
<h3>Main Life and career events</h3>
<ul>
<li>
<p>1952 | Elizabeth accedes to the throne on the death of her father, George VI.</p>
</li>
<li>
<p>1952 | World's first jet airliner passenger service inaugurated by BOAC in Comet I aircraft</p>
</li>
<li>
<p>1953 | Edmund Hillary and Tenzing Norgay climb Mount Everest just before Coronation Day</p>
</li>
<li>
<p>1953 | Francis Crick and James Watson unravel the mystery of DNA</p>
</li>
<li>
<p>1953 | - 1954 Queen Elizabeth and Prince Philip embark on a 6 month world tour including Australia and New Zealand</p>
</li>
<li>
<p>1955 | Winston Churchill resigns as Prime Minister and is succeeded by Anthony Eden.</p>
</li>
<li>
<p>1955 | Laws restricting the burning of coal and establishing smokeless zones bring an end to London's notorious fogs</p>
</li>
<li>
<p>1956 | Anglo-French forces invade Egypt after the nationalization of the Suez Canal.</p>
</li>
<li>
<p>1957 | Harold Macmillan becomes Prime Minister</p>
</li>
<li>
<p>1957 | The Gold Coast becomes independent as Ghana, the first British colony in Africa to receive its independence.</p>
</li>
<li>
<p>1957 | Queen Elizabeth addresses the United Nations and opens the 23rd Canadian Parliament</p>
</li>
<li>
<p>1959 | Oil is discovered in the North Sea.</p>
</li>
<li>
<p>1959 | Queen Elizabeth tours Canada and the United States</p>
</li>
<li>
<p>1960 | Harold Macmillan becomes Prime Minister makes 'winds of change' speech in South Africa.</p>
</li>
<li>
<p>1960 | Union of South Africa withdraws from the Commonwealth.</p>
</li>
<li>
<p>1962 | Jamaica gains independence</p>
</li>
<li>
<p>1963 | Alec Douglas-Hume replaces Harold Macmillan as the Prime Minister.</p>
</li>
<li>
<p>1963 | The Beatles release their first LP.</p>
</li>
<li>
<p>1964 | Labour government of Harold Wilson takes office</p>
</li>
<li>
<p>1966 | Aberfan disaster leaves 116 children dead</p>
</li>
<li>
<p>1967 | Capital punishment abolished in the UK for murder, and one year later for all crimes</p>
</li>
<li>
<p>1969 | Prince Charles is invested as Prince of Wales.</p>
</li>
<li>
<p>1969 | Troubles break out in the North of Ireland</p>
</li>
<li>
<p>1970 | Edward Heath becomes Prime Minister.</p>
</li>
<li>
<p>1971 | Decimal currency is introduced.</p>
</li>
<li>
<p>1973 | The United Kingdom joins the European Economic Community (EEC)</p>
</li>
<li>
<p>1974 | Miners strike brings down Heath Government. Harold Wilson returns as Prime Minister.</p>
</li>
<li>
<p>1976 | Concorde begins first supersonic trans-Atlantic flights</p>
</li>
<li>
<p>1977 | Celebration of the Silver Jubilee of the Queens accession</p>
</li>
<li>
<p>1978 | The world's first test-tube baby is delivered in Oldham, Greater Manchester</p>
</li>
<li>
<p>1979 | Margaret Thatcher succeeds James Callaghan, becoming Britain’s first woman Prime Minister.</p>
</li>
<li>
<p>1981 | Prince Charles marries Lady Diana Spencer in St. Paul’s Cathedral.</p>
</li>
<li>
<p>1982 | Unemployment in Britain tops three million.</p>
</li>
<li>
<p>1982 | Britain goes to war with Argentina over control of the Falkland Islands</p>
</li>
<li>
<p>1982 | Pope John Paul II is first reigning pope to visit the UK.</p>
</li>
<li>
<p>1984 | Miners strike again but is defeated by Thatcher.</p>
</li>
<li>
<p>1986 | Queen Elizabeth II celebrates 60th birthday.</p>
</li>
<li>
<p>1988 | PanAm flight 103 bombed and crashes on Lockerbie killing 270</p>
</li>
<li>
<p>1989 | Poll tax is introduced amid widespread protest.</p>
</li>
<li>
<p>1989 | Fall of the Berlin Wall. End of the 'Cold War'.</p>
</li>
<li>
<p>1990 | Margaret Thatcher resigns as Prime Minister after 11 years and is succeeded by John Major.</p>
</li>
<li>
<p>1991 | The Allied forces liberate Kuwait during the Gulf War.</p>
</li>
<li>
<p>1992 | Princess Anne and Mark Phillips divorce. Windsor castle suffers severe fire damage.</p>
</li>
<li>
<p>1993 | Maastricht Treaty. The EEC becomes the European Union and the European Parliament comes into force.</p>
</li>
<li>
<p>1994 | Opening of the Channel Tunnel between England and France</p>
</li>
<li>
<p>1996 | Both the Prince and Princess of Wales, and the Duke and Duchess of York divorce.</p>
</li>
<li>
<p>1997 | Tony Blair becomes Prime Minister and ends 18 years of Conservative government.</p>
</li>
<li>
<p>1997 | Hong Kong reverts to China after 155 years of British rule.</p>
</li>
<li>
<p>1997 | Diana Princess of Wales dies in Paris car crash</p>
</li>
<li>
<p>1998 | Good Friday agreement in Northern Ireland</p>
</li>
<li>
<p>1998 | Scotland and Wales vote for their own Assemblies</p>
</li>
<li>
<p>1999 | Edward, Earl of Wessex, marries Sophie Rhys-Jones.</p>
</li>
<li>
<p>2000 | Queen Mother celebrates her 100th birthday.</p>
</li>
<li>
<p>2001 | Twin towers of the World Trade Center in New York destroyed by Islamic terrorists.</p>
</li>
<li>
<p>2001 | - 2014. Fourth Afghan War. British and Allied troops in Afghanistan.</p>
</li>
<li>
<p>2002 | Queen Elizabeth II marks her Golden Jubilee of 50 years of rule. Deaths of Queen Mother and Princess Margaret.</p>
</li>
<li>
<p>2003 | British and US forces invade Iraq and topple Saddam Hussein</p>
</li>
<li>
<p>2005 | Prince Charles marries his second wife Camilla Parker-Bowles and she is given the title Duchess of Cornwall</p>
</li>
<li>
<p>2006 | Queen Elizabeth II celebrates her 80th birthday.</p>
</li>
<li>
<p>2007 | Tony Blair resigns as Prime Minister</p>
</li>
<li>
<p>2007 | Queen Elizabeth II and her husband Prince Philip celebrate 60 years of marriage</p>
</li>
<li>
<p>2007 | Queen Elizabeth II becomes the oldest ever reigning British monarch</p>
</li>
<li>
<p>2008 | World wide banking crisis. Government has to bail out two major British banks</p>
</li>
<li>
<p>2009 | Parliamentary integrity damaged by expenses scandal</p>
</li>
<li>
<p>2010 | David Cameron becomes Prime Minister</p>
</li>
<li>
<p>2011 | Prince William marries Catherine Middleton. They become Duke and Duchess of Cambridge.</p>
</li>
<li>
<p>2011 | Queen Elizabeth II visits Dublin in the first state visit to the Republic of Ireland by a reigning British monarch.</p>
</li>
<li>
<p>2012 | Queen Elizabeth II celebrates her Diamond Jubilee of 60 years since her accession to the throne.</p>
</li>
<li>
<p>2012 | Queen Elizabeth II opens the London 2012 Olympic Games</p>
</li>
<li>
<p>2013 | Birth of Prince George, son of the Duke and Duchess of Cambridge</p>
</li>
<li>
<p>2014 | Scottish voters reject proposal by the Scottish National Party to leave the United Kingdom</p>
</li>
<li>
<p>2014 | End of 4th Afghan war. British forces leave Afghanistan.</p>
</li>
<li>
<p>2015 | Birth of Princess Charlotte, daughter of the Duke and Duchess of Cambridge</p>
</li>
<li>
<p>2015 | Queen Elizabeth II becomes the longest ever reigning British monarch surpassing her great-great-grandmother Queen Victoria.</p>
</li>
<li>
<p>2016 | Queen Elizabeth II celebrates her 90th birthday.</p>
</li>
<li>
<p>2016 | The United Kingdom votes to leave the European Union.</p>
</li>
<li>
<p>2016 | David Cameron resigns as Prime Minister and is replaced by Theresa May.</p>
</li>
<li>
<p>2017 | The UK negotiates to regain sovereignty from the European Union.</p>
</li>
<li>
<p>2018 | Birth of Prince Louis, second son of the Duke and Duchess of Cambridge</p>
</li>
<li>
<p>2018 | Prince Harry marries Meghan Markle. They become Duke and Duchess of Sussex.</p>
</li>
<li>
<p>2019 | Boris Johnson becomes Prime Minister</p>
</li>
<li>
<p>2020 | Prince Harry and his wife exit royal duties and move to North America</p>
</li>
<li>
<p>2020 | The United Kingdom leaves the European Union</p>
</li>
<li>
<p>2020 | Worldwide coronavirus pandemic</p>
</li>
</ul>
